/**
 * QuickChart.io Integration
 * 
 * Generuje grafy z demografických dat.
 * API je zdarma, žádný klíč potřeba.
 * https://quickchart.io/documentation/
 */

export interface ChartData {
  type: 'bar' | 'line' | 'doughnut' | 'pie' | 'horizontalBar';
  title: string;
  labels: string[];
  datasets: Array<{
    label: string;
    data: number[];
    backgroundColor?: string | string[];
    borderColor?: string;
  }>;
}

/**
 * Structured photography preset — per-project configuration that drives
 * the entire Imagen pipeline. No hardcoded fallbacks.
 * 
 * Can be set manually in Visual Identity tab or auto-generated by Hugo AI
 * from project KB + description.
 */
export interface PhotographyPreset {
  // Core prompt directives (what the photo SHOULD look like)
  style: string;              // e.g. 'documentary', 'editorial', 'lifestyle', 'architectural', 'product', 'portrait'
  mood: string;               // e.g. 'warm and authentic', 'cool and professional', 'energetic and dynamic'
  lighting: string;           // e.g. 'natural daylight', 'golden hour', 'studio soft light', 'overcast diffused'
  color_grade: string;        // e.g. 'warm tones, slight film grain', 'desaturated muted palette', 'vibrant and saturated'
  composition: string;        // e.g. 'rule of thirds, shallow DOF', 'centered subject, clean background'
  // Subject & context
  typical_subjects: string;   // e.g. 'Czech families, young couples, urban apartments, nature'
  typical_settings: string;   // e.g. 'modern Czech apartments, Prague streets, office interiors'
  // Negative prompt (what to AVOID — sent as separate negativePrompt to Imagen API)
  negative_prompt: string;    // e.g. 'stock photo poses, fake smiles, clipart, text overlays, watermarks'
  // Technical
  camera_style: string;       // e.g. 'mirrorless 35mm f/1.8', 'iPhone 15 Pro', 'medium format Hasselblad'
  // Quality control
  sample_count: number;       // How many variants to generate (1-4), best picked by Gemini Vision
  quality_threshold: number;  // Min Gemini Vision score (1-10) to accept, below = regenerate
  max_retries: number;        // Max regeneration attempts before fallback
  // Post-processing (Sharp pipeline)
  post_processing: {
    sharpen: boolean;         // Subtle sharpening for crisp details
    denoise: boolean;         // Remove AI noise artifacts
    film_grain: number;       // 0 = none, 0.1-0.5 = subtle, 0.5+ = heavy (adds realism)
    saturation: number;       // 0.8 = desaturated, 1.0 = normal, 1.2 = vibrant
    contrast: number;         // 0.9 = flat, 1.0 = normal, 1.1 = punchy
    warmth: number;           // -0.1 = cool, 0 = neutral, 0.1 = warm
  };
}

export const DEFAULT_PHOTOGRAPHY_PRESET: PhotographyPreset = {
  style: 'candid documentary',
  mood: 'authentic and natural',
  lighting: 'natural ambient light',
  color_grade: 'natural colors, slight warmth',
  composition: 'rule of thirds, environmental context',
  typical_subjects: '',
  typical_settings: '',
  negative_prompt: 'stock photo poses, fake smiles, plastic skin, AI artifacts, extra fingers, text overlays, watermarks, logos, overly saturated colors, symmetrical poses',
  camera_style: 'full-frame mirrorless, 35mm f/2.0, shallow depth of field',
  sample_count: 2,
  quality_threshold: 6,
  max_retries: 2,
  post_processing: {
    sharpen: true,
    denoise: true,
    film_grain: 0.15,
    saturation: 1.0,
    contrast: 1.05,
    warmth: 0.02,
  },
};

export interface VisualIdentity {
  primary_color: string;
  secondary_color: string;
  accent_color: string;
  text_color: string;
  font: string;
  logo_url: string | null;
  style: string;
  // Photography & AI image generation settings (legacy — use photography_preset instead)
  photography_style?: string;
  photography_mood?: string;
  photography_subjects?: string;
  photography_avoid?: string;
  photography_lighting?: string;
  photography_color_grade?: string;
  photography_reference?: string;
  brand_visual_keywords?: string;
  // Structured photography preset — drives the entire Imagen pipeline per-project
  photography_preset?: PhotographyPreset;
  // Text overlay settings for compositing text on photos
  text_overlay?: {
    enabled: boolean;
    position: 'top' | 'center' | 'bottom';
    max_chars: number;
    max_lines: number;
    uppercase: boolean;
    font_size_ratio: number;       // % of image width, e.g. 0.045 = 4.5%
    font_weight: 'normal' | 'bold';
    bg_style: 'box' | 'gradient' | 'shadow_only' | 'none';
    bg_opacity: number;            // 0-1
    text_color: string;            // hex, e.g. '#FFFFFF'
    accent_color: string;          // hex, for numbers/highlights
    padding_ratio: number;         // % of image width, e.g. 0.06
    highlight_numbers: boolean;    // render numbers in accent_color
  };
}

const DEFAULT_IDENTITY: VisualIdentity = {
  primary_color: '#1a1a2e',
  secondary_color: '#16213e',
  accent_color: '#0f3460',
  text_color: '#ffffff',
  font: 'Inter',
  logo_url: null,
  style: 'minimal',
};

/**
 * Generate a chart URL via QuickChart.io
 * Returns a URL to a PNG image of the chart
 */
export function generateChartUrl(
  chartData: ChartData,
  identity: Partial<VisualIdentity> = {},
): string {
  const vi = { ...DEFAULT_IDENTITY, ...identity };

  const config = {
    type: chartData.type,
    data: {
      labels: chartData.labels,
      datasets: chartData.datasets.map((ds, i) => ({
        ...ds,
        backgroundColor: ds.backgroundColor || [vi.primary_color, vi.accent_color, vi.secondary_color, '#e94560', '#533483'][i] || vi.primary_color,
        borderColor: ds.borderColor || 'transparent',
        borderWidth: 0,
      })),
    },
    options: {
      title: {
        display: !!chartData.title,
        text: chartData.title,
        fontColor: vi.text_color,
        fontSize: 18,
        fontFamily: vi.font,
      },
      legend: {
        labels: {
          fontColor: vi.text_color,
          fontFamily: vi.font,
        },
      },
      scales: chartData.type !== 'doughnut' && chartData.type !== 'pie' ? {
        xAxes: [{
          ticks: { fontColor: vi.text_color, fontFamily: vi.font },
          gridLines: { color: 'rgba(255,255,255,0.1)' },
        }],
        yAxes: [{
          ticks: { fontColor: vi.text_color, fontFamily: vi.font, beginAtZero: true },
          gridLines: { color: 'rgba(255,255,255,0.1)' },
        }],
      } : undefined,
      plugins: {
        datalabels: {
          color: vi.text_color,
          font: { size: 14, family: vi.font, weight: 'bold' },
          display: true,
        },
      },
    },
  };

  const chartConfig = encodeURIComponent(JSON.stringify(config));

  return `https://quickchart.io/chart?c=${chartConfig}&w=800&h=500&bkg=${encodeURIComponent(vi.primary_color)}&f=png`;
}

/**
 * Pre-built chart templates for common data visualizations
 */
export const CHART_TEMPLATES = {
  // Poměr pracujících k důchodcům
  workerRatio: (identity?: Partial<VisualIdentity>): string => generateChartUrl({
    type: 'bar',
    title: 'Pracující na 1 důchodce',
    labels: ['Dnes (2024)', '2035', '2050'],
    datasets: [{
      label: 'Poměr',
      data: [3, 2.5, 2],
      backgroundColor: ['#0f3460', '#e94560', '#e94560'],
    }],
  }, identity),

  // Porodnost v ČR
  fertilityRate: (identity?: Partial<VisualIdentity>): string => generateChartUrl({
    type: 'line',
    title: 'Porodnost v ČR (dětí na ženu)',
    labels: ['2015', '2017', '2019', '2021', '2023', '2024'],
    datasets: [{
      label: 'Porodnost',
      data: [1.57, 1.69, 1.71, 1.83, 1.45, 1.37],
      borderColor: '#e94560',
      backgroundColor: 'rgba(233,69,96,0.2)',
    }, {
      label: 'Potřeba pro udržení populace',
      data: [2.1, 2.1, 2.1, 2.1, 2.1, 2.1],
      borderColor: '#ffffff',
      backgroundColor: 'transparent',
    }],
  }, identity),

  // Stárnutí populace
  agingPopulation: (identity?: Partial<VisualIdentity>): string => generateChartUrl({
    type: 'doughnut',
    title: 'Populace 65+ v roce 2050',
    labels: ['Pod 65 let (70 %)', 'Nad 65 let (30 %)'],
    datasets: [{
      label: 'Podíl',
      data: [70, 30],
      backgroundColor: ['#0f3460', '#e94560'],
    }],
  }, identity),

  // Důchod vs nájem
  pensionVsRent: (identity?: Partial<VisualIdentity>): string => generateChartUrl({
    type: 'horizontalBar',
    title: 'Měsíční příjem (Kč)',
    labels: ['Státní důchod', 'Splátka hypotéky 2+kk', 'Nájem 2+kk Brno'],
    datasets: [{
      label: 'Kč/měsíc',
      data: [20736, 14200, 16000],
      backgroundColor: ['#e94560', '#0f3460', '#16213e'],
    }],
  }, identity),
};
