-- ============================================
-- Migration 022: Cross-project dedup + Engagement metrics
-- ============================================

-- 1. Add embedding column to content_queue for cross-project dedup
ALTER TABLE content_queue ADD COLUMN IF NOT EXISTS embedding vector(768);
ALTER TABLE content_queue ADD COLUMN IF NOT EXISTS engagement_metrics jsonb;
ALTER TABLE content_queue ADD COLUMN IF NOT EXISTS engagement_score integer DEFAULT 0;

-- 2. Index for cross-project similarity search
CREATE INDEX IF NOT EXISTS idx_content_queue_embedding
  ON content_queue USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 50);

CREATE INDEX IF NOT EXISTS idx_content_queue_engagement
  ON content_queue (engagement_score DESC)
  WHERE engagement_score > 0;

-- 3. RPC function: match posts across ALL projects (excluding source project)
CREATE OR REPLACE FUNCTION match_posts_cross_project(
  query_embedding vector(768),
  exclude_project_id uuid,
  match_threshold float DEFAULT 0.7,
  match_count int DEFAULT 5
)
RETURNS TABLE (
  id uuid,
  project_id uuid,
  project_name text,
  text_content text,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    cq.id,
    cq.project_id,
    p.name AS project_name,
    cq.text_content,
    1 - (cq.embedding <=> query_embedding) AS similarity
  FROM content_queue cq
  JOIN projects p ON p.id = cq.project_id
  WHERE cq.project_id != exclude_project_id
    AND cq.embedding IS NOT NULL
    AND cq.status IN ('approved', 'sent', 'scheduled', 'published', 'review')
    AND 1 - (cq.embedding <=> query_embedding) > match_threshold
  ORDER BY cq.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- 4. Trigger: auto-generate embedding when post is created/updated
CREATE OR REPLACE FUNCTION auto_embed_post()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  -- Embedding will be generated by the application layer (Gemini text-embedding-004)
  -- This trigger just marks posts that need embedding
  IF NEW.text_content IS NOT NULL AND NEW.embedding IS NULL THEN
    -- Flag for async processing (handled by cron)
    NEW.needs_embedding = true;
  END IF;
  RETURN NEW;
END;
$$;

-- Add needs_embedding flag
ALTER TABLE content_queue ADD COLUMN IF NOT EXISTS needs_embedding boolean DEFAULT false;

-- Create trigger (only on insert, not update to avoid loops)
DROP TRIGGER IF EXISTS trg_auto_embed_post ON content_queue;
CREATE TRIGGER trg_auto_embed_post
  BEFORE INSERT ON content_queue
  FOR EACH ROW
  EXECUTE FUNCTION auto_embed_post();
